### ISSUE TITLE
`except/e` Contract Errors when passed > 10 args

### ISSUE THREAD

**Issue by maxsnew** [racket/data#13]
The contract of`except/e` special cases to just use or/e when 10 or fewer arguments are passed, but when 10 or more are passed it tries to do something smart with hashing, but it doesn't seem to work correctly.

So for instance if I remove 10 elements from an enum it works fine:
```
> (enum->list (apply except/e (below/e 100) (enum->list (below/e 10))))
...
```
But if I try to remove 11 at once I get an error:
```
> (from-nat (apply except/e (below/e 100) (enum->list (below/e 11))) 0)
hash-ref: no value found for key
  key: #f
```

**Comment by rfindler** [comment]
Looks like this was fixed in in October of 2016? 

https://github.com/racket/data/commit/29d8c99b786ad5a95676325f41456a7f18648213

**Comment by maxsnew** [comment]
Oh lol I really ought to update

**Comment by rfindler** [comment]
:)
