### ISSUE TITLE
fix/e would be nice for data/enumerate

### ISSUE THREAD

**Issue by LeifAndersen** [racket/data#3]
I have a recursive data type that I need to create an enumeration for. Currently the only way to do this is to use `delay/e` from the racket docs:

```
(letrec ([bt/e (delay/e
                  (or/e (single/e #f)
                        (list/e bt/e bt/e)))])
    (enum->list bt/e 5))
```

It would much more clean (or at least straightforward) to have a `fix/e`.

**Comment by rfindler** [comment]
(define-syntax-rule (fix/e e) (letrec ([x (delay/e e)]) x))?

I guess you'd want to fix up error messages, too? And accept all those
extra arguments? PRs welcome :)

**Comment by LeifAndersen** [comment]
lol, okay, works for me. Thanks. :)
