### ISSUE TITLE
`enum->stream` should be in public interface.

### ISSUE THREAD

**Issue by LeifAndersen** [racket/data#5]
`enum->stream` is in the compat lib (as `to-stream`), but should be in the current library as well. I would be happy to add documentation for it if there is no opposition to the idea.

**Comment by rfindler** [comment]
Why should it be there? Can you not use a sequence?

**Comment by LeifAndersen** [comment]
Ah, I didn't really know the difference between a stream and a sequence. @takikawa just explained it to me. And yup, that works. Thank you.

**Comment by rfindler** [comment]
Oh, good! (I wasn't completely sure myself)
